### ISSUE TITLE
能详细出一个React的umi-request的代理配置代码吗？

### ISSUE THREAD

**Issue by aohanhongzhi** [gefeiyanga/blog#8]
blog/笔记/umi-request&axios.md

**Comment by gefeiyanga** [comment]
/** Request 网络请求工具 更详细的 api 文档: https://github.com/umijs/umi-request */
import { extend } from 'umi-request';
import { notification } from 'antd';
import { logoutSuccessCallback } from '@/utils/util';

// export const baseUrl = '/local_analysis';
// export const baseUrl = '';
// export const baseUrl = 'http://192.168.1.55:8192/local_analysis';

const codeMessage: { [status: number]: string } = {
  200: '服务器成功返回请求的数据。',
  201: '新建或修改数据成功。',
  202: '一个请求已经进入后台排队（异步任务）。',
  204: '删除数据成功。',
  400: '发出的请求有错误，服务器没有进行新建或修改数据的操作。',
  401: '用户没有权限（令牌、用户名、密码错误）。',
  403: '用户得到授权，但是访问是被禁止的。',
  404: '发出的请求针对的是不存在的记录，服务器没有进行操作。',
  406: '请求的格式不可得。',
  410: '请求的资源被永久删除，且不会再得到的。',
  422: '当创建一个对象时，发生一个验证错误。',
  500: '服务器发生错误，请检查服务器。',
  502: '网关错误。',
  503: '服务不可用，服务器暂时过载或维护。',
  504: '网关超时。',
  700: '用户未登录。',
  701: '用户已在其他地点登录。',
  702: '用户已过期，请重新登录。',
};

/** 异常处理程序 */
const errorHandler = (error: { response: Response }): Response => {
  const { response } = error;
  if (response && response.status) {
    const errorText = codeMessage[response.status] || response.statusText;
    const { status, url } = response;

    notification.error({
      message: `请求错误 ${status}: ${url}`,
      description: errorText,
    });
    if (
      response.status == 700 ||
      response.status == 701 ||
      response.status == 702
    ) {
      logoutSuccessCallback('请重新登录！');
    }
  } else if (!response) {
    notification.error({
      description: '您的网络发生异常，无法连接服务器',
      message: '网络异常',
    });
  }
  return response;
};

/** 配置request请求时的默认参数 */
const request = extend({
  // prefix: baseUrl,
  errorHandler, // 默认错误处理
  credentials: 'include', // 默认请求是否带上cookie
  mode: 'cors',
  headers: {
    'Content-Type': 'application/json',
    Accept: '*/*',
    token: JSON.parse(localStorage.getItem('userInfo') || '{}').cookie,
  },
});
request.interceptors.request.use((url, options) => {
  return {
    url: url,
    options: {
      ...options,
      headers: {
        'Content-Type': 'application/json',
        Accept: '*/*',
        token: JSON.parse(localStorage.getItem('userInfo') || '{}').cookie,
      },
    },
  };
});

export default request;

**Comment by gefeiyanga** [comment]
```
/** Request 网络请求工具 更详细的 api 文档: https://github.com/umijs/umi-request */
import { extend } from 'umi-request';
import { notification } from 'antd';
import { logoutSuccessCallback } from '@/utils/util';

// export const baseUrl = '/local_analysis';
// export const baseUrl = '';
// export const baseUrl = 'http://192.168.1.55:8192/local_analysis';

const codeMessage: { [status: number]: string } = {
  200: '服务器成功返回请求的数据。',
  201: '新建或修改数据成功。',
  202: '一个请求已经进入后台排队（异步任务）。',
  204: '删除数据成功。',
  400: '发出的请求有错误，服务器没有进行新建或修改数据的操作。',
  401: '用户没有权限（令牌、用户名、密码错误）。',
  403: '用户得到授权，但是访问是被禁止的。',
  404: '发出的请求针对的是不存在的记录，服务器没有进行操作。',
  406: '请求的格式不可得。',
  410: '请求的资源被永久删除，且不会再得到的。',
  422: '当创建一个对象时，发生一个验证错误。',
  500: '服务器发生错误，请检查服务器。',
  502: '网关错误。',
  503: '服务不可用，服务器暂时过载或维护。',
  504: '网关超时。',
  700: '用户未登录。',
  701: '用户已在其他地点登录。',
  702: '用户已过期，请重新登录。',
};

/** 异常处理程序 */
const errorHandler = (error: { response: Response }): Response => {
  const { response } = error;
  if (response && response.status) {
    const errorText = codeMessage[response.status] || response.statusText;
    const { status, url } = response;

    notification.error({
      message: `请求错误 ${status}: ${url}`,
      description: errorText,
    });
    if (
      response.status == 700 ||
      response.status == 701 ||
      response.status == 702
    ) {
      logoutSuccessCallback('请重新登录！');
    }
  } else if (!response) {
    notification.error({
      description: '您的网络发生异常，无法连接服务器',
      message: '网络异常',
    });
  }
  return response;
};

/** 配置request请求时的默认参数 */
const request = extend({
  // prefix: baseUrl,
  errorHandler, // 默认错误处理
  credentials: 'include', // 默认请求是否带上cookie
  mode: 'cors',
  headers: {
    'Content-Type': 'application/json',
    Accept: '*/*',
    token: JSON.parse(localStorage.getItem('userInfo') || '{}').cookie,
  },
});
request.interceptors.request.use((url, options) => {
  return {
    url: url,
    options: {
      ...options,
      headers: {
        'Content-Type': 'application/json',
        Accept: '*/*',
        token: JSON.parse(localStorage.getItem('userInfo') || '{}').cookie,
      },
    },
  };
});

export default request;
```

**Comment by gefeiyanga** [comment]
> blog/笔记/umi-request&axios.m

> blog/笔记/umi-request&axios.md

**Comment by gefeiyanga** [comment]
> blog/笔记/umi-request&axios.md

还有记得配置proxy
